### ISSUE TITLE
Question: 3 Questions.

### ISSUE THREAD

**Issue by charlieporth1** [jamesandariese/issh#2]
Is issh encrypted at all? Is there an issh daemond? and is it faster than SNMP?

**Comment by jamesandariese** [comment]
1)
issh is encrypted but the key is not random unless you generate a random seed.

The purpose of issh is to allow you to create force commands easily, usually for use with nagios or similar systems.

It is meant as an alternative to snmp without forcing you to setup (or understand how to setup) snmp securely.

2)
There is no isshd.  it is meant to be used with a standard sshd such as openssh which supports ssh-dss keys and the command keyword in authorized_keys (this is the actual security mechanism -- do not skip it!)

3)
It is probably slower than snmp by a good deal in CPU time terms but it's been used successfully as a replacement for it without anyone noticing undue burden on the CPU, mainly because the CPU time used, while probably on the order of 1000x (a guess but probably not an unreasonable one), is generally inconsequential in today's tech economy (a similar amount of work is done every time you make a new request to an SSL enabled website, for example).

Of course, if your SNMP setup is secured with any encryption, they should be similarly complex to compute.  issh is meant to replace insecure SNMP setups by adding security which entails adding CPU time.  if you have SNMP setup already and your SNMP setup is actually secure already, issh will probably have a similar speed but, issh is probably not for you then since you've already invested in the system which this is meant to bypass.

99)

If you have any other questions, I'm happy to answer them!

Also, remember that issh isn't meant to be secure (though, in reality it can be as secure as any ssh client using DSA keys if you treat the keys properly, though they are deprecated) and that it is meant to keep you from having to learn how to properly secure SNMP while getting similar security to a properly secured SNMP solution.   The security for issh is from configuring your forced commands to be fast running, non-damaging, and to not expose information that you wouldn't expose via a basic auth https website or something similar on your internal network (another solution commonly used to keep from having to setup SNMP).

Do not use issh on a public facing ssh server without using a seed with a significant random element (a uuidv4 or something of that nature would work).  Preferably, do not use it on a public facing ssh server at all.
